//
//  SMStyleKit.m
//  AugmentedRealityWeatherApp
//
//  Created by Shaun Merritt on 9/24/14.
//  Copyright (c) 2014 Shaun Merritt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "SMStyleKit.h"


@implementation SMStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (UIBezierPath *)drawLocationIcon;
{
    
    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(28.9, 13.1)];
    [bezierPath addCurveToPoint: CGPointMake(17.76, 33.03) controlPoint1: CGPointMake(24.72, 18.99) controlPoint2: CGPointMake(19.75, 25.02)];
    [bezierPath addCurveToPoint: CGPointMake(17.76, 44.25) controlPoint1: CGPointMake(17.54, 39.44) controlPoint2: CGPointMake(16.65, 40.88)];
    [bezierPath addCurveToPoint: CGPointMake(61.08, 119.02) controlPoint1: CGPointMake(17.07, 60.94) controlPoint2: CGPointMake(46.99, 122.56)];
    [bezierPath addCurveToPoint: CGPointMake(99.44, 52.97) controlPoint1: CGPointMake(73.3, 115.94) controlPoint2: CGPointMake(94.96, 66.53)];
    [bezierPath addCurveToPoint: CGPointMake(99.44, 40.51) controlPoint1: CGPointMake(99.54, 45.76) controlPoint2: CGPointMake(100.65, 44.15)];
    [bezierPath addCurveToPoint: CGPointMake(68.5, 1.88) controlPoint1: CGPointMake(98.89, 19.99) controlPoint2: CGPointMake(85.24, 6.09)];
    [bezierPath addCurveToPoint: CGPointMake(28.9, 13.1) controlPoint1: CGPointMake(45.29, -1.86) controlPoint2: CGPointMake(40.72, 7.14)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(48.7, 33.03)];
    [bezierPath addCurveToPoint: CGPointMake(44.99, 38.02) controlPoint1: CGPointMake(48.03, 34.97) controlPoint2: CGPointMake(45.81, 36.38)];
    [bezierPath addCurveToPoint: CGPointMake(53.65, 56.71) controlPoint1: CGPointMake(44.49, 48.17) controlPoint2: CGPointMake(47.51, 53.62)];
    [bezierPath addCurveToPoint: CGPointMake(72.22, 47.99) controlPoint1: CGPointMake(63.73, 57.21) controlPoint2: CGPointMake(69.15, 54.17)];
    [bezierPath addCurveToPoint: CGPointMake(63.55, 29.29) controlPoint1: CGPointMake(72.72, 37.84) controlPoint2: CGPointMake(69.69, 32.39)];
    [bezierPath addCurveToPoint: CGPointMake(48.7, 33.03) controlPoint1: CGPointMake(53.36, 27.72) controlPoint2: CGPointMake(53.52, 30.61)];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;

    return bezierPath;
}

@end
