//
//  SMStyleKit.h
//  AugmentedRealityWeatherApp
//
//  Created by Shaun Merritt on 9/24/14.
//  Copyright (c) 2014 Shaun Merritt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface SMStyleKit : NSObject

// Drawing Methods
+ (UIBezierPath *)drawLocationIcon;
+ (NSArray *)drawiPhone;


@end
